#!/bin/bash

# Parameters as documented in githooks(5)
prev_head="${1}"
curr_head="${2}"
flag="${3}"

# If prev_head is all zeros, then this is a git-clone
if [[ $prev_head =~ ^0+$ ]] ; then
    if [ -r .upstream ] ; then
        git remote add upstream "$(<.upstream)"
    fi
fi
