#!/bin/bash

main()
{
	# Parameters as documented in githooks(5)
	local prev_head="${1}"
	local curr_head="${2}"
	local flag="${3}"

	# If prev_head is all zeros, then this is a git-clone
	if [[ $prev_head =~ ^0+$ ]] ; then
		set_user_by_origin
	fi
}

set_user_by_origin()
{
	local origin="$(git remote get-url origin)"
	case "${origin}" in
		*github.com/sluidfoe/*)
			git config user.name 'sluidfoe'
			git config user.email 'sluidfoe@gmail.com'
			;;
	esac
}

main "$@"
