#!/bin/bash

# Network manager fix - allow all users to modify settings.
# This is suboptimal, but will continue to track this bug/feature.
mv -f /usr/share/crunchbang/adduser.conf /etc/adduser.conf
dpkg-divert --quiet --add "/etc/adduser.conf"
mv -f /usr/share/crunchbang/org.freedesktop.NetworkManager.pkla /etc/polkit-1/localauthority/50-local.d/org.freedesktop.NetworkManager.pkla
dpkg-divert --quiet --add "/etc/polkit-1/localauthority/50-local.d/org.freedesktop.NetworkManager.pkla"
groupadd -g 900 cbnetwork
NOOB=`awk -F: '{print $1}' /etc/passwd | tail -1`
usermod -a -G cbnetwork ${NOOB}
usermod -a -G fuse ${NOOB}

# udisks - allow all users to mount internal drives within Thunar
mv -f /usr/share/crunchbang/10-udisks.pkla /etc/polkit-1/localauthority/50-local.d/10-udisks.pkla
dpkg-divert --quiet -add "/etc/polkit-1/localauthority/50-local.d/10-udisks.pkla"

# Move final apt source file into place.
mv -f /etc/apt/sources-list-post-preseed /etc/apt/sources.list

# Remove live-* packages as no longer needed.
dpkg --purge live-boot live-config-sysvinit live-boot-initramfs-tools live-build live-config live-helper live-initramfs debootstrap gnu-fdisk

# This is a fugly hack for fixing fstab after installing
# CrunchBang using unetbootin. Basically, if using unetbootin,
# the USB device is identified as a cdrom drive and added to
# /etc/fstab as that. This script will find any such entries
# in fstab and disable them. It is looking for cdrom entries
# which reference devices under "/dev/sdX".
FSTAB=/etc/fstab
if grep "^/dev/sd" ${FSTAB} | grep "/media/" | grep "auto"
then
    NEEDLE=`grep "^/dev/sd" ${FSTAB} | grep "/media/" | grep "auto"`
    if ! echo "${NEEDLE}" | grep "#/dev/sd"
    then
        CORK="#${NEEDLE}"
        rpl -q "${NEEDLE}" "${CORK}" ${FSTAB}
    fi
fi
exit 0
